sudo: false
language: node_js
node_js:
  - 'stable'
services:
  - mongodb
cache:
  directories:
    - 'node_modules'
before_script:
  - sleep 15
script:
  - npm run test
after_success: npm run coverage